### ISSUE TITLE
Limit delay between transactions

### ISSUE THREAD

**Issue by Boyan-MILANOV** [crytic/optik#78]
`hybrid-echidna` makes the delay between transactions symbolic, since it might affect the behaviour of contracts and be the cause of a bug. However, we should constrain the delay to a "reasonable" value in the context of an attack. 

Echidna uses a ;ax delay of 1 week

**Comment by ggrieco-tob** [comment]
This is relevant: https://github.com/crytic/echidna/blob/31034fbf8d147911ba2176522dc11d3a0a490a35/lib/Echidna/Types/Tx.hs#L29-L45
