### ISSUE TITLE
Support `STATICCALL` and `DELEGATECALL`

### ISSUE THREAD

**Issue by Boyan-MILANOV** [crytic/optik#86]
We should add proper support for `STATICCALL` and  `DELEGATECALL` operations

**Comment by ggrieco-tob** [comment]
Is it `CALL` already supported? For using optik in audits, the highest priority will be doing calls to the same deployed contract to perform try/catch operations and detect unexpected reverts.

**Comment by Boyan-MILANOV** [comment]
All calls are already supported, except for `DELEGATECALL` which is a little bit more annoying to handle because contracts must share the same storage
